# Generated by Django 3.2.3 on 2021-07-08 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterConsumed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2o_oz', models.IntegerField()),
                ('day_time', models.DateTimeField(auto_now=True)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietjournal.logentry')),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedtime', models.DateTimeField()),
                ('waketime', models.DateTimeField()),
                ('sleep_quality', models.TextField()),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietjournal.logentry')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=200)),
                ('reaction', models.TextField()),
                ('day_time', models.DateTimeField(auto_now=True)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietjournal.logentry')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('meal_num', models.IntegerField()),
                ('food', models.CharField(max_length=200)),
                ('drink', models.CharField(max_length=200)),
                ('mood', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('day_time', models.DateTimeField(auto_now=True)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietjournal.logentry')),
            ],
        ),
        migrations.CreateModel(
            name='BowelMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bm_num', models.IntegerField()),
                ('notes', models.TextField()),
                ('day_time', models.DateTimeField(auto_now=True)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietjournal.logentry')),
            ],
        ),
    ]
