# Generated by Django 3.2.3 on 2021-07-13 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dietjournal', '0002_auto_20210708_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaterConsumed',
            new_name='Water',
        ),
        migrations.RemoveField(
            model_name='bowelmovement',
            name='bm_num',
        ),
        migrations.RemoveField(
            model_name='bowelmovement',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='food',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_num',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='reaction',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='reason',
        ),
        migrations.AddField(
            model_name='bowelmovement',
            name='bm_note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_summary',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('note', models.TextField(default='')),
                ('day_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietjournal.logentry')),
            ],
        ),
    ]
